checks:
    php: true

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true

build:
    environment:
        variables:
            NVM_NODEJS_ORG_MIRROR: 'https://nodejs.org/dist'
            NODEJS_ORG_MIRROR: 'https://nodejs.org/dist'
    nodes:
        analysis:
            image: default-jammy
            environment:
                php: 8.3.0
                node: 20
            tests:
                override:
                    - php-scrutinizer-run

tools:
    external_code_coverage:
        timeout: 600
        runs: 1

build_failure_conditions:
    - 'elements.rating(<= C).new.exists' # No new classes/methods with a rating of C or worse allowed
    - 'issues.severity(>= MAJOR).new.exists' # New issues of major or higher severity
    - 'patches.label("Unused Use Statements").new.exists' # No new unused imports patches allowed
