networks:
    dilps-tiresias-net:
        driver: bridge

name: dilps-tiresias

services:
    dilps-tiresias-app:
        image: unillett/dilps-tiresias:latest
        build:
            context: ./dev/config
            dockerfile: ./app.dockerfile
        env_file:
            - ./dev/.env
        volumes:
            - ./:/var/www
            - ./dev/config/pool-www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./dev/config/pool-thumbnails.conf:/usr/local/etc/php-fpm.d/thumbnails.conf
            - ./dev/config/zz-pool-docker.conf:/usr/local/etc/php-fpm.d/zz-thumbnails-docker.conf
        working_dir: /var/www
        expose:
            - '9000'
            - '9100'
        networks:
            - dilps-tiresias-net
        container_name: dilps-tiresias-app

    dilps-tiresias-httpd:
        image: httpd:latest
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs
            - ./configuration/apache.conf:/usr/local/apache2/conf/global.conf
            - ./dev/config/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./dev/config/httpd-mpm.conf:/usr/local/apache2/conf/extra/httpd-mpm.conf
            - ./dev/config/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
        ports:
            - '8181:80'
        depends_on:
            - dilps-tiresias-app
        networks:
            - dilps-tiresias-net
        container_name: dilps-tiresias-httpd

    dilps-tiresias-mysql:
        image: mariadb:10.6
        env_file:
            - ./dev/.env
        volumes:
            - mysql-data:/var/lib/mysql
            - ./dev/config/my.cnf:/etc/mysql/my.cnf
        ports:
            - '3301:3306'
        networks:
            - dilps-tiresias-net
        container_name: dilps-tiresias-mysql

    dilps-tiresias-myadmin:
        image: phpmyadmin/phpmyadmin:latest
        env_file:
            - ./dev/.env
        ports:
            - '9797:80'
        networks:
            - dilps-tiresias-net
        container_name: dilps-tiresias-myadmin

    dilps-tiresias-mailhog:
        image: mailhog/mailhog:latest
        expose:
            - '1025'
        ports:
            - '8027:8025'
        networks:
            - dilps-tiresias-net
        container_name: dilps-tiresias-mailhog

volumes:
    mysql-data:
