<?php declare(strict_types=1); ?>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <title><?php echo $this->escapeHtml($this->subject) ?></title>
        <style type="text/css">
            div.footer {
                margin-top: 3em;
                font-size: 0.8em;
            }
        </style>
    </head>
    <body>
        <p>Bonjour<?php echo $this->escapeHtml($this->user && $this->user->getName() ? ' ' . $this->user->getName() : '') ?>,</p>

        <?php echo $this->content; ?>

        <div class="footer">
            <p>
                Ceci est un message automatique de notification envoyé par
                <a href="<?php echo $this->serverUrl ?>"><?php echo $this->escapeHtml($this->hostname) ?>.</a>
            </p>
        </div>
    </body>
</html>
