name: ci
on: [push, pull_request]
jobs:
    test:
        name: PHP${{ matrix.php-versions }}
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                php-versions: ['8.1', '8.2']

        env:
            MYSQL_HOST: '127.0.0.1'

        services:
            mariadb:
                image: mariadb:10.4
                ports:
                    - 3306:3306
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: dilps
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=5

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Node Setup
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: PHP Setup
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: pcov
                  tools: cs2pr
                  extensions: imagick

            - name: Show PHP version
              run: php -v

            - name: Cache composer
              uses: actions/cache@v3
              with:
                  path: ~/.cache/composer
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Cache Yarn
              uses: actions/cache@v3
              with:
                  path: ~/.cache/yarn
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Setup problem matchers for PHP
              run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Prepare app
              run: |
                  mysql --protocol=tcp --user=root --execute='SET GLOBAL sql_mode = "";'
                  cp example.env .env
                  cp config/autoload/local.php.dist config/autoload/local.php

            - name: Build app
              id: app-build
              env:
                  GENERATE_MAP: true
              run: ./bin/build.sh

            - name: Load test data
              run: ./bin/load-test-data.php

            - name: PHP CS Fixer
              run: ./vendor/bin/php-cs-fixer fix --format=checkstyle | cs2pr

            - name: PHPStan
              run: ./vendor/bin/phpstan analyse

            - name: Lint
              id: app-lint
              run: yarn lint

            - name: Prettier
              id: app-prettier
              run: ./node_modules/.bin/prettier --check .

            - name: Test PHP
              id: app-test-php
              run: ./vendor/bin/phpunit --coverage-clover coverage-clover.xml

            - name: Test Angular
              id: app-test-ng
              run: ./node_modules/.bin/ng test --progress false --watch=false --browsers ChromeHeadlessCustom

            - name: Upload code coverage
              run: |
                  composer global require scrutinizer/ocular
                  ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage-clover.xml

            - name: Upload sources map artifact
              id: upload-artifact
              uses: actions/upload-artifact@v3
              if: ${{ matrix.php-versions == '8.1' }}
              with:
                  name: js-sources-map
                  path: ${{ github.workspace }}/htdocs
