name: docker
on:
    push:
        branches:
            - 'develop'
            - 'master'

env:
    DOCKERHUB_REPOSITORY: unillett/dilps-tiresias

jobs:
    docker:
        name: Build & Push
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./dev/config
                  file: ./dev/config/app.dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ env.DOCKERHUB_REPOSITORY }}:latest
                  cache-from: type=registry,ref=${{ env.DOCKERHUB_REPOSITORY }}:latest
                  cache-to: type=inline

            - name: Update description
              uses: peter-evans/dockerhub-description@v4
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                  repository: ${{ env.DOCKERHUB_REPOSITORY }}
